name: GitHub Actions Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "boildjob"

  test-job:
    runs-on: ubuntu-lastest
    steps:
      - run: echo "test jobs"

  deploy-job:
    runs-on: ubuntu-lastest
    steps:
      - run: echo "deploy job to prodrution server"
